[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "twtrexcs"
author = "Michael Savin"
author-email = "jtprogru@gmail.com"
home-page = "https://github.com/jtprogru/twitter-excuse"
description-file = "README.md"

